/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq;


import com.wan.jooqdemo.Dao.jooq.tables.Datatest;
import com.wan.jooqdemo.Dao.jooq.tables.Student;
import com.wan.jooqdemo.Dao.jooq.tables.Zonedatatest;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>userinfo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATATEST_PRIMARY = Indexes0.DATATEST_PRIMARY;
    public static final Index STUDENT_PRIMARY = Indexes0.STUDENT_PRIMARY;
    public static final Index ZONEDATATEST_PRIMARY = Indexes0.ZONEDATATEST_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATATEST_PRIMARY = Internal.createIndex("PRIMARY", Datatest.DATATEST, new OrderField[] { Datatest.DATATEST.USERID }, true);
        public static Index STUDENT_PRIMARY = Internal.createIndex("PRIMARY", Student.STUDENT, new OrderField[] { Student.STUDENT.SID }, true);
        public static Index ZONEDATATEST_PRIMARY = Internal.createIndex("PRIMARY", Zonedatatest.ZONEDATATEST, new OrderField[] { Zonedatatest.ZONEDATATEST.ID }, true);
    }
}
