/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq;


import com.wan.jooqdemo.Dao.jooq.tables.Datatest;
import com.wan.jooqdemo.Dao.jooq.tables.Student;
import com.wan.jooqdemo.Dao.jooq.tables.Zonedatatest;
import com.wan.jooqdemo.Dao.jooq.tables.records.DatatestRecord;
import com.wan.jooqdemo.Dao.jooq.tables.records.StudentRecord;
import com.wan.jooqdemo.Dao.jooq.tables.records.ZonedatatestRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>userinfo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DatatestRecord, Integer> IDENTITY_DATATEST = Identities0.IDENTITY_DATATEST;
    public static final Identity<StudentRecord, Integer> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<ZonedatatestRecord, Integer> IDENTITY_ZONEDATATEST = Identities0.IDENTITY_ZONEDATATEST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatatestRecord> KEY_DATATEST_PRIMARY = UniqueKeys0.KEY_DATATEST_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<ZonedatatestRecord> KEY_ZONEDATATEST_PRIMARY = UniqueKeys0.KEY_ZONEDATATEST_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DatatestRecord, Integer> IDENTITY_DATATEST = Internal.createIdentity(Datatest.DATATEST, Datatest.DATATEST.USERID);
        public static Identity<StudentRecord, Integer> IDENTITY_STUDENT = Internal.createIdentity(Student.STUDENT, Student.STUDENT.SID);
        public static Identity<ZonedatatestRecord, Integer> IDENTITY_ZONEDATATEST = Internal.createIdentity(Zonedatatest.ZONEDATATEST, Zonedatatest.ZONEDATATEST.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DatatestRecord> KEY_DATATEST_PRIMARY = Internal.createUniqueKey(Datatest.DATATEST, "KEY_datatest_PRIMARY", Datatest.DATATEST.USERID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.SID);
        public static final UniqueKey<ZonedatatestRecord> KEY_ZONEDATATEST_PRIMARY = Internal.createUniqueKey(Zonedatatest.ZONEDATATEST, "KEY_zonedatatest_PRIMARY", Zonedatatest.ZONEDATATEST.ID);
    }
}
