/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq;


import com.wan.jooqdemo.Dao.jooq.tables.Datatest;
import com.wan.jooqdemo.Dao.jooq.tables.Person;
import com.wan.jooqdemo.Dao.jooq.tables.Score;
import com.wan.jooqdemo.Dao.jooq.tables.Student;
import com.wan.jooqdemo.Dao.jooq.tables.Usertest;
import com.wan.jooqdemo.Dao.jooq.tables.Zonedatatest;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in userinfo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>userinfo.datatest</code>.
     */
    public static final Datatest DATATEST = Datatest.DATATEST;

    /**
     * The table <code>userinfo.person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>userinfo.score</code>.
     */
    public static final Score SCORE = Score.SCORE;

    /**
     * The table <code>userinfo.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>userinfo.usertest</code>.
     */
    public static final Usertest USERTEST = Usertest.USERTEST;

    /**
     * The table <code>userinfo.zonedatatest</code>.
     */
    public static final Zonedatatest ZONEDATATEST = Zonedatatest.ZONEDATATEST;
}
