/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq;


import com.wan.jooqdemo.Dao.jooq.tables.Datatest;
import com.wan.jooqdemo.Dao.jooq.tables.Person;
import com.wan.jooqdemo.Dao.jooq.tables.Score;
import com.wan.jooqdemo.Dao.jooq.tables.Student;
import com.wan.jooqdemo.Dao.jooq.tables.Usertest;
import com.wan.jooqdemo.Dao.jooq.tables.Zonedatatest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userinfo extends SchemaImpl {

    private static final long serialVersionUID = -496160236;

    /**
     * The reference instance of <code>userinfo</code>
     */
    public static final Userinfo USERINFO = new Userinfo();

    /**
     * The table <code>userinfo.datatest</code>.
     */
    public final Datatest DATATEST = com.wan.jooqdemo.Dao.jooq.tables.Datatest.DATATEST;

    /**
     * The table <code>userinfo.person</code>.
     */
    public final Person PERSON = com.wan.jooqdemo.Dao.jooq.tables.Person.PERSON;

    /**
     * The table <code>userinfo.score</code>.
     */
    public final Score SCORE = com.wan.jooqdemo.Dao.jooq.tables.Score.SCORE;

    /**
     * The table <code>userinfo.student</code>.
     */
    public final Student STUDENT = com.wan.jooqdemo.Dao.jooq.tables.Student.STUDENT;

    /**
     * The table <code>userinfo.usertest</code>.
     */
    public final Usertest USERTEST = com.wan.jooqdemo.Dao.jooq.tables.Usertest.USERTEST;

    /**
     * The table <code>userinfo.zonedatatest</code>.
     */
    public final Zonedatatest ZONEDATATEST = com.wan.jooqdemo.Dao.jooq.tables.Zonedatatest.ZONEDATATEST;

    /**
     * No further instances allowed
     */
    private Userinfo() {
        super("userinfo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Datatest.DATATEST,
            Person.PERSON,
            Score.SCORE,
            Student.STUDENT,
            Usertest.USERTEST,
            Zonedatatest.ZONEDATATEST);
    }
}
