server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://rm-bp1n51icgfyg5c75z9o.mysql.rds.aliyuncs.com:3306/userinfo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: HMW505991
    username: wanminghui
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
   prefix: classpath:/templates/
   encoding: UTF-8
   cache: false
   suffix: .html