/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq.tables;


import com.wan.jooqdemo.Dao.jooq.Indexes;
import com.wan.jooqdemo.Dao.jooq.Keys;
import com.wan.jooqdemo.Dao.jooq.Userinfo;
import com.wan.jooqdemo.Dao.jooq.tables.records.DatatestRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Datatest extends TableImpl<DatatestRecord> {

    private static final long serialVersionUID = -171984655;

    /**
     * The reference instance of <code>userinfo.datatest</code>
     */
    public static final Datatest DATATEST = new Datatest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatatestRecord> getRecordType() {
        return DatatestRecord.class;
    }

    /**
     * The column <code>userinfo.datatest.userid</code>.
     */
    public final TableField<DatatestRecord, Integer> USERID = createField(DSL.name("userid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>userinfo.datatest.starttime</code>.
     */
    public final TableField<DatatestRecord, LocalDateTime> STARTTIME = createField(DSL.name("starttime"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>userinfo.datatest.endtime</code>.
     */
    public final TableField<DatatestRecord, LocalDateTime> ENDTIME = createField(DSL.name("endtime"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>userinfo.datatest</code> table reference
     */
    public Datatest() {
        this(DSL.name("datatest"), null);
    }

    /**
     * Create an aliased <code>userinfo.datatest</code> table reference
     */
    public Datatest(String alias) {
        this(DSL.name(alias), DATATEST);
    }

    /**
     * Create an aliased <code>userinfo.datatest</code> table reference
     */
    public Datatest(Name alias) {
        this(alias, DATATEST);
    }

    private Datatest(Name alias, Table<DatatestRecord> aliased) {
        this(alias, aliased, null);
    }

    private Datatest(Name alias, Table<DatatestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Datatest(Table<O> child, ForeignKey<O, DatatestRecord> key) {
        super(child, key, DATATEST);
    }

    @Override
    public Schema getSchema() {
        return Userinfo.USERINFO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATATEST_PRIMARY);
    }

    @Override
    public Identity<DatatestRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DATATEST;
    }

    @Override
    public UniqueKey<DatatestRecord> getPrimaryKey() {
        return Keys.KEY_DATATEST_PRIMARY;
    }

    @Override
    public List<UniqueKey<DatatestRecord>> getKeys() {
        return Arrays.<UniqueKey<DatatestRecord>>asList(Keys.KEY_DATATEST_PRIMARY);
    }

    @Override
    public Datatest as(String alias) {
        return new Datatest(DSL.name(alias), this);
    }

    @Override
    public Datatest as(Name alias) {
        return new Datatest(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Datatest rename(String name) {
        return new Datatest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Datatest rename(Name name) {
        return new Datatest(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
