/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person implements Serializable {

    private static final long serialVersionUID = 885799180;

    private Integer pid;
    private String  pname;
    private String  paddr;

    public Person() {}

    public Person(Person value) {
        this.pid = value.pid;
        this.pname = value.pname;
        this.paddr = value.paddr;
    }

    public Person(
        Integer pid,
        String  pname,
        String  paddr
    ) {
        this.pid = pid;
        this.pname = pname;
        this.paddr = paddr;
    }

    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    @Size(max = 20)
    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    @Size(max = 50)
    public String getPaddr() {
        return this.paddr;
    }

    public void setPaddr(String paddr) {
        this.paddr = paddr;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Person (");

        sb.append(pid);
        sb.append(", ").append(pname);
        sb.append(", ").append(paddr);

        sb.append(")");
        return sb.toString();
    }
}
