/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Score implements Serializable {

    private static final long serialVersionUID = 81422014;

    private Integer sid;
    private String  sname;
    private Integer scores;

    public Score() {}

    public Score(Score value) {
        this.sid = value.sid;
        this.sname = value.sname;
        this.scores = value.scores;
    }

    public Score(
        Integer sid,
        String  sname,
        Integer scores
    ) {
        this.sid = sid;
        this.sname = sname;
        this.scores = scores;
    }

    public Integer getSid() {
        return this.sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    @Size(max = 20)
    public String getSname() {
        return this.sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public Integer getScores() {
        return this.scores;
    }

    public void setScores(Integer scores) {
        this.scores = scores;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Score (");

        sb.append(sid);
        sb.append(", ").append(sname);
        sb.append(", ").append(scores);

        sb.append(")");
        return sb.toString();
    }
}
