/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = -1801263881;

    private Integer sid;
    private String  sname;
    private Integer sage;

    public Student() {}

    public Student(Student value) {
        this.sid = value.sid;
        this.sname = value.sname;
        this.sage = value.sage;
    }

    public Student(
        Integer sid,
        String  sname,
        Integer sage
    ) {
        this.sid = sid;
        this.sname = sname;
        this.sage = sage;
    }

    public Integer getSid() {
        return this.sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    @Size(max = 20)
    public String getSname() {
        return this.sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public Integer getSage() {
        return this.sage;
    }

    public void setSage(Integer sage) {
        this.sage = sage;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(sid);
        sb.append(", ").append(sname);
        sb.append(", ").append(sage);

        sb.append(")");
        return sb.toString();
    }
}
