/*
 * This file is generated by jOOQ.
 */
package com.wan.jooqdemo.Dao.jooq.tables.records;


import com.wan.jooqdemo.Dao.jooq.tables.Student;

import javax.annotation.processing.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -1369749803;

    /**
     * Setter for <code>userinfo.student.sid</code>.
     */
    public void setSid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>userinfo.student.sid</code>.
     */
    public Integer getSid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>userinfo.student.sname</code>.
     */
    public void setSname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>userinfo.student.sname</code>.
     */
    @Size(max = 20)
    public String getSname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>userinfo.student.sage</code>.
     */
    public void setSage(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>userinfo.student.sage</code>.
     */
    public Integer getSage() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.SID;
    }

    @Override
    public Field<String> field2() {
        return Student.STUDENT.SNAME;
    }

    @Override
    public Field<Integer> field3() {
        return Student.STUDENT.SAGE;
    }

    @Override
    public Integer component1() {
        return getSid();
    }

    @Override
    public String component2() {
        return getSname();
    }

    @Override
    public Integer component3() {
        return getSage();
    }

    @Override
    public Integer value1() {
        return getSid();
    }

    @Override
    public String value2() {
        return getSname();
    }

    @Override
    public Integer value3() {
        return getSage();
    }

    @Override
    public StudentRecord value1(Integer value) {
        setSid(value);
        return this;
    }

    @Override
    public StudentRecord value2(String value) {
        setSname(value);
        return this;
    }

    @Override
    public StudentRecord value3(Integer value) {
        setSage(value);
        return this;
    }

    @Override
    public StudentRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer sid, String sname, Integer sage) {
        super(Student.STUDENT);

        set(0, sid);
        set(1, sname);
        set(2, sage);
    }
}
